services:
  user-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${USER_DB_USERNAME}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    ports:
      - '${USER_DB_HOST_PORT}:5432'
    volumes:
      - user-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  notification-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${NOTIFICATION_DB_NAME}
      POSTGRES_USER: ${NOTIFICATION_DB_USERNAME}
      POSTGRES_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
    ports:
      - '${NOTIFICATION_DB_HOST_PORT}:5432'
    volumes:
      - notification-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  user-service:
    build:
      context: .
      args:
        SERVICE_NAME: user
    ports:
      - '${USER_SERVICE_PORT}:${USER_SERVICE_PORT}'
    environment:
      DB_NAME: ${USER_DB_NAME}
      PORT: ${USER_SERVICE_PORT}
      DB_PORT: ${USER_SERVICE_DB_PORT}
      DB_HOST: ${USER_SERVICE_DB_HOST}
      DB_USERNAME: ${USER_DB_USERNAME}
      DB_PASSWORD: ${USER_DB_PASSWORD}
      NOTIFICATION_SERVICE_URL: ${NOTIFICATION_SERVICE_URL}
    depends_on:
      - user-db
      - notification-service
    restart: unless-stopped

  notification-service:
    build:
      context: .
      args:
        SERVICE_NAME: notification
    ports:
      - '${NOTIFICATION_SERVICE_PORT}:${NOTIFICATION_SERVICE_PORT}'
    environment:
      DB_NAME: ${NOTIFICATION_DB_NAME}
      PORT: ${NOTIFICATION_SERVICE_PORT}
      DB_PORT: ${NOTIFICATION_SERVICE_DB_PORT}
      DB_USERNAME: ${NOTIFICATION_DB_USERNAME}
      DB_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
      DB_HOST: ${NOTIFICATION_SERVICE_DB_HOST}
    depends_on:
      - notification-db
    restart: unless-stopped

volumes:
  user-db-data:
  notification-db-data:
