services:
  user-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${USER_DB_USERNAME}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    ports:
      - '${USER_DB_HOST_PORT}:5432'
    volumes:
      - user-db-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '${RABBITMQ_PORT}:5672'
      - '15672:15672'
    environment:
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 5s
    restart: unless-stopped

  notification-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${NOTIFICATION_DB_NAME}
      POSTGRES_USER: ${NOTIFICATION_DB_USERNAME}
      POSTGRES_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
    ports:
      - '${NOTIFICATION_DB_HOST_PORT}:5432'
    volumes:
      - notification-db-data:/var/lib/postgresql/data

  user-service:
    build:
      context: .
      target: deps
    ports:
      - '${USER_SERVICE_PORT}:${USER_SERVICE_PORT}'
    environment:
      DB_NAME: ${USER_DB_NAME}
      PORT: ${USER_SERVICE_PORT}
      DB_HOST: ${USER_SERVICE_DB_HOST}
      DB_PORT: ${USER_SERVICE_DB_PORT}
      DB_USERNAME: ${USER_DB_USERNAME}
      DB_PASSWORD: ${USER_DB_PASSWORD}
      NOTIFICATION_SERVICE_URL: ${NOTIFICATION_SERVICE_URL}
      RABBITMQ_URL: amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:${RABBITMQ_PORT}
    depends_on:
      user-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      notification-service:
        condition: service_started
    volumes:
      - ./apps/user-service:/app/apps/user-service
      - ./libs:/app/libs
      - ./nest-cli.json:/app/nest-cli.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.build.json:/app/tsconfig.build.json
    command: pnpm run start:dev:user-service

  notification-service:
    build:
      context: .
      target: deps
    ports:
      - '${NOTIFICATION_SERVICE_PORT}:${NOTIFICATION_SERVICE_PORT}'
    environment:
      WEBHOOK_URL: ${WEBHOOK_URL}
      DB_NAME: ${NOTIFICATION_DB_NAME}
      PORT: ${NOTIFICATION_SERVICE_PORT}
      DB_HOST: ${NOTIFICATION_SERVICE_DB_HOST}
      DB_PORT: ${NOTIFICATION_SERVICE_DB_PORT}
      DB_USERNAME: ${NOTIFICATION_DB_USERNAME}
      DB_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
      RABBITMQ_URL: amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:${RABBITMQ_PORT}
    depends_on:
      rabbitmq:
        condition: service_healthy
      notification-db:
        condition: service_started
    volumes:
      - ./apps/notification-service:/app/apps/notification-service
      - ./libs:/app/libs
      - ./nest-cli.json:/app/nest-cli.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.build.json:/app/tsconfig.build.json
    command: pnpm run start:dev:notification-service

volumes:
  user-db-data:
  rabbitmq-data:
  notification-db-data:
